[package]
name = "rust-bcf"
version = "0.1.0"
authors = ["Till Hartmann <till.hartmann@udo.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bgzip = "0.1"
itertools = "0.9"
anyhow = "1.0"
nom = "6.0"
num_enum = "0.5"
num_enum_derive = "0.5"
strum = { version = "0.19", features = ["derive"] }